# On every push this script is executed
on: push
name: Build and deploy GH Pages
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/zola'
    steps:
      - name: checkout
        uses: actions/checkout@v3.0.0
      - name: build_and_deploy
        uses: shalzz/zola-deploy-action@v0.17.2
        env:
          PAGES_BRANCH: gh-pages
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
#  deploy:
#    environment:
#      name: github-pages
#      url: btwiusearch.net
#    runs-on: ubuntu-latest
#    needs: build
#    steps:
#      - name: Deploy to GitHub Pages
#        id: deployment
#        uses: actions/deploy-pages@v2
#
# On every push this script is executed
# on: push
# name: Build and deploy GH Pages
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     if: github.ref == 'refs/heads/zola'
#     steps:
#       - name: checkout
#         uses: actions/checkout@v3.0.0
#       - name: build_and_deploy
#         uses: shalzz/zola-deploy-action@v0.17.2
#         env:
#           # Target branch
#           PAGES_BRANCH: gh-pages
#           # Or if publishing to the same repo, use the automatic token
#           TOKEN: ${{ secrets.GITHUB_TOKEN }}
